### ISSUE TITLE
wen update? 

### ISSUE THREAD

**Issue by mxriox** [yobro2033/WallesterGEN#1]
when running it only prints:
card
card
card
card

without any cards being generated or saved in the .txt file

hope youre still around to fix it would really appreciate it <3

**Comment by yobro2033** [comment]
What a German way to start a conversation.

Apparently a few people are still using the exact script the past couple of days and it still working. There will be no update under any circumstances because I’ve left Wallester for over a year and no longer have an accounts with them.

**Comment by mxriox** [comment]
> What a German way to start a conversation.
> 
> Apparently a few people are still using the exact script the past couple of days and it still working. There will be no update under any circumstances because I’ve left Wallester for over a year and no longer have an accounts with them.

A little ice breaker hehe but damn ok thats interesting lets see if i can get it working again too thanks for the info!
