### ISSUE TITLE
regarding public key

### ISSUE THREAD

**Issue by mxriox** [yobro2033/WallesterGEN#2]
I think i might be using the wrong one or whatever (i am a total noob so bare with me setting up took me 3hs to get it running xd) but i cant get any key displayed using webinspector but if i click the grey lock -> show certificate -> the public key is the  SHA-256-Fingerabdruck  ?

Thanks a lot!

**Comment by yobro2033** [comment]
The instructions are very clear. If you pay me maybe lmao.

**Comment by MilanSapkota04** [comment]
how much

**Comment by yobro2033** [comment]
50?

**Comment by MilanSapkota04** [comment]
Can you do 10?

**Comment by yobro2033** [comment]
im not gonna wasting my time for 10 specially it's easter LMAO
